local h = require("tests.harness")
local codex = require("codex")
local config = require("codex.config")

local function with_editor(callback, backend_name)
  backend_name = backend_name or "terminal"
  local module_name = backend_name == "terminal" and "codex.terminal" or "codex.app_server"
  local original_backend = package.loaded[module_name]
  local original_notify = vim.notify
  local original_select = vim.ui.select
  local original_buf = vim.api.nvim_get_current_buf()
  local directory = vim.fn.tempname()
  vim.fn.mkdir(directory, "p")
  directory = assert(vim.uv.fs_realpath(directory))
  local path = directory .. "/source.lua"
  vim.fn.writefile({ "local one = 1", "local two = 2" }, path)
  local bufnr = vim.fn.bufadd(path)
  vim.fn.bufload(bufnr)
  vim.api.nvim_set_current_buf(bufnr)
  vim.bo[bufnr].filetype = "lua"
  local fixture = {
    bufnr = bufnr,
    path = path,
    sends = {},
    notifications = {},
    status = { backend = backend_name, running = false, visible = false },
  }
  package.loaded[module_name] = {
    status = function()
      return vim.deepcopy(fixture.status)
    end,
    send = function(text, opts)
      table.insert(fixture.sends, { text = text, opts = opts })
      return true
    end,
  }
  rawset(vim, "notify", function(message)
    table.insert(fixture.notifications, message)
  end)
  config.setup({ backend = backend_name, cwd = "file" })
  local ok, err = xpcall(function()
    callback(fixture)
  end, debug.traceback)
  if package.loaded["codex.ask"] then
    require("codex.ask").reset()
  end
  rawset(vim, "notify", original_notify)
  rawset(vim.ui, "select", original_select)
  package.loaded[module_name] = original_backend
  vim.api.nvim_set_current_buf(original_buf)
  vim.api.nvim_buf_delete(bufnr, { force = true })
  vim.fn.delete(directory, "rf")
  if not ok then
    error(err, 0)
  end
end

h.test("request guidance follows input mode without becoming request text", function()
  with_editor(function(f)
    h.truthy(codex.ask())
    local ask = require("codex.ask")
    local function footer_text()
      return table.concat(vim.tbl_map(function(chunk)
        return chunk[1]
      end, vim.api.nvim_win_get_config(0).footer or {}))
    end
    local function header_text()
      return vim.api.nvim_eval_statusline(vim.wo.winbar, {
        winid = vim.api.nvim_get_current_win(),
        use_winbar = true,
        maxwidth = 24,
      }).str
    end
    h.contains(header_text(), "Ctrl-S")
    local insert_hint
    local insert_header
    vim.keymap.set("i", "<F8>", function()
      insert_hint = footer_text()
      insert_header = header_text()
    end, { buf = 0 })
    vim.api.nvim_feedkeys(vim.keycode("<Esc>i<F8>first line<CR>second line<Esc>"), "xt", false)
    h.contains(insert_hint, "Type your request")
    h.contains(insert_hint, "Ctrl-S")
    h.contains(insert_header, "Ctrl-S")
    h.contains(insert_hint, "Enter")
    h.contains(footer_text(), "Press i")
    h.contains(header_text(), "Ctrl-S")
    vim.cmd("normal! ggV")
    h.contains(footer_text(), "Press Esc")
    vim.api.nvim_feedkeys(vim.keycode("<Esc>"), "nx", false)
    h.eq(0, #f.sends)
    local text = table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "\n")
    h.contains(text, "first line\nsecond line")
    h.eq(nil, text:find("Type your request", 1, true))
    h.truthy(ask.submit())
    h.eq(text, f.sends[1].text)
    h.truthy(codex.ask())
    h.contains(footer_text(), "queued")
    h.eq(nil, footer_text():find("Ctrl-S", 1, true))
    h.eq(nil, header_text():find("Ctrl-S", 1, true))
    f.sends[1].opts.on_complete(false)
    h.eq(true, vim.bo.modifiable)
    h.contains(footer_text(), "Ctrl-S")
    h.contains(header_text(), "Ctrl-S")
  end)
end)

h.test("ask keeps exact selected text until explicit submission", function()
  with_editor(function(f)
    vim.cmd("normal! gg06lvj2l")
    vim.api.nvim_feedkeys(vim.keycode("<Esc>"), "nx", false)
    h.truthy(codex.ask_visual("Explain this code"))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    h.eq("codex://ask", vim.api.nvim_buf_get_name(draft))
    h.eq(0, #f.sends)
    local text = table.concat(vim.api.nvim_buf_get_lines(draft, 0, -1, false), "\n")
    h.contains(text, "one = 1\nlocal two")
    h.eq(nil, text:find("local one", 1, true))
    vim.api.nvim_buf_set_lines(f.bufnr, 0, -1, false, { "changed after selection" })
    h.truthy(ask.submit())
    h.eq(1, #f.sends)
    h.contains(f.sends[1].text, "Explain this code")
    h.contains(f.sends[1].text, "one = 1\nlocal two")
    h.contains(f.sends[1].text, "@" .. f.path)
    h.eq(vim.fs.dirname(f.path), f.sends[1].opts.cwd)
    h.eq(true, f.sends[1].opts.submit)
    h.eq(false, vim.bo[draft].modifiable)
    h.eq(false, ask.submit())
    f.sends[1].opts.on_complete(true)
    h.eq(false, vim.api.nvim_buf_is_valid(draft))
    h.eq(f.bufnr, vim.api.nvim_get_current_buf())
  end)
end)

h.test("follow-up composes from the panel without attaching terminal output", function()
  with_editor(function(f)
    f.status = { backend = "terminal", running = true, jobid = 42, cwd = vim.fs.dirname(f.path) }
    vim.bo[f.bufnr].buftype = "nofile"
    h.truthy(codex.follow_up("Also explain the tradeoff"))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    h.eq({ "Also explain the tradeoff" }, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.eq(false, ask.add_diagnostics())
    h.truthy(ask.submit())
    h.eq("Also explain the tradeoff", f.sends[1].text)
    h.eq(f.status.cwd, f.sends[1].opts.cwd)
    f.sends[1].opts.on_complete(true)
    h.eq(false, vim.api.nvim_buf_is_valid(draft))
  end)
end)

h.test("follow-up keeps its draft when the conversation stops or changes", function()
  with_editor(function(f)
    h.eq(false, codex.follow_up())
    h.eq(f.bufnr, vim.api.nvim_get_current_buf())
    f.status = { backend = "app_server", running = true, jobid = 42, thread_id = "first", cwd = vim.fs.dirname(f.path) }
    h.truthy(codex.follow_up("Check the previous result"))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    f.status.thread_id = "second"
    h.eq(false, ask.submit())
    f.status.thread_id = "first"
    f.status.jobid = 43
    h.eq(false, ask.submit())
    f.status.jobid = 42
    f.status.running = false
    h.eq(false, ask.submit())
    h.eq(0, #f.sends)
    h.eq({ "Check the previous result" }, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.eq(true, vim.bo[draft].modifiable)
  end, "app_server")
end)

h.test("submission leaves the source window active for the backend and reopens a failed draft", function()
  with_editor(function(f)
    local source_win = vim.api.nvim_get_current_win()
    h.truthy(codex.ask("Explain"))
    local draft = vim.api.nvim_get_current_buf()
    h.truthy(require("codex.ask").submit())
    h.eq(source_win, vim.api.nvim_get_current_win())
    h.eq({}, vim.fn.win_findbuf(draft))
    f.sends[1].opts.on_complete(false)
    h.eq(draft, vim.api.nvim_get_current_buf())
    h.eq(true, vim.bo[draft].modifiable)
  end)
end)

h.test("ask retains editable drafts after delivery failure and when hidden", function()
  with_editor(function(f)
    h.truthy(codex.ask("Fix the bug", 1, 1))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    local lines = vim.api.nvim_buf_get_lines(draft, 0, -1, false)
    h.truthy(ask.hide())
    h.eq(f.bufnr, vim.api.nvim_get_current_buf())
    h.truthy(codex.ask())
    h.eq(draft, vim.api.nvim_get_current_buf())
    h.eq(lines, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.truthy(ask.submit())
    f.sends[1].opts.on_complete(false)
    h.eq(true, vim.bo[draft].modifiable)
    h.eq(lines, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.truthy(ask.submit())
    h.eq(2, #f.sends)
  end)
end)

h.test("ask actions and diagnostics use the source selection rather than the prompt buffer", function()
  with_editor(function(f)
    local namespace = vim.api.nvim_create_namespace("codex_ask_test")
    vim.diagnostic.set(namespace, f.bufnr, {
      { lnum = 0, col = 6, message = "first diagnostic", severity = vim.diagnostic.severity.ERROR },
      { lnum = 1, col = 6, message = "second diagnostic", severity = vim.diagnostic.severity.WARN },
    })
    h.truthy(codex.ask(nil, 2, 2))
    local ask = require("codex.ask")
    rawset(vim.ui, "select", function(items, _, callback)
      callback(items[3])
    end)
    ask.choose_action()
    h.eq(0, #f.sends)
    h.truthy(ask.add_diagnostics())
    h.truthy(ask.submit())
    local text = f.sends[1].text
    h.contains(text, "tests")
    h.contains(text, "second diagnostic")
    h.contains(text, "2:7")
    h.eq(nil, text:find("first diagnostic", 1, true))
    vim.diagnostic.reset(namespace, f.bufnr)
  end)
end)

h.test("ask submits edited context through the app-server backend", function()
  with_editor(function(f)
    h.truthy(codex.ask("Explain", 1, 1))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    local other = vim.fs.dirname(f.path) .. "/other.lua"
    vim.fn.writefile({ "return true" }, other)
    h.truthy(ask.add_file(other))
    local lines = vim.api.nvim_buf_get_lines(draft, 0, -1, false)
    h.contains(table.concat(lines, "\n"), "@" .. other)
    vim.api.nvim_buf_set_lines(draft, 0, -1, false, { "Only answer this edited request" })
    h.truthy(ask.submit())
    h.eq("Only answer this edited request", f.sends[1].text)
    h.eq(vim.fs.dirname(f.path), f.sends[1].opts.cwd)
    f.sends[1].opts.on_complete(true)
  end, "app_server")
end)

h.test("ask rejects oversized additions and submission without losing the draft", function()
  with_editor(function(f)
    h.truthy(codex.ask("Explain", 1, 1))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    local lines = vim.api.nvim_buf_get_lines(draft, 0, -1, false)
    config.setup({ cwd = "file", context = { max_lines = 1, max_bytes = 10 } })
    h.eq(false, ask.add_file(f.path))
    h.eq(lines, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.eq(false, ask.submit())
    h.eq(0, #f.sends)
    h.eq(true, vim.bo[draft].modifiable)
    h.contains(table.concat(f.notifications, "\n"), "limit")
  end)
end)

h.test("ask preserves unsaved buffer content and rejects a changed backend", function()
  with_editor(function(f)
    vim.api.nvim_buf_set_lines(f.bufnr, 0, -1, false, { "unsaved change" })
    h.truthy(codex.ask("Explain"))
    local draft = vim.api.nvim_get_current_buf()
    h.contains(table.concat(vim.api.nvim_buf_get_lines(draft, 0, -1, false), "\n"), "unsaved change")
    config.setup({ backend = "app_server" })
    h.eq(false, require("codex.ask").submit())
    h.eq(0, #f.sends)
    h.eq({ "local one = 1", "local two = 2" }, vim.fn.readfile(f.path))
  end)
end)

h.test("delivery callbacks preserve newer edits and do not consume a replacement draft", function()
  with_editor(function(f)
    h.truthy(codex.ask("Original request"))
    local ask = require("codex.ask")
    local draft = vim.api.nvim_get_current_buf()
    h.truthy(ask.submit())
    vim.bo[draft].modifiable = true
    vim.api.nvim_buf_set_lines(draft, 0, -1, false, { "Newer draft edits" })
    f.sends[1].opts.on_complete(true)
    h.eq({ "Newer draft edits" }, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.truthy(ask.submit())
    vim.cmd.bdelete({ args = { tostring(draft) }, bang = true })
    vim.api.nvim_set_current_buf(f.bufnr)
    h.truthy(codex.ask("Replacement request"))
    local replacement = vim.api.nvim_get_current_buf()
    f.sends[2].opts.on_complete(true)
    h.truthy(vim.api.nvim_buf_is_valid(replacement))
    h.contains(table.concat(vim.api.nvim_buf_get_lines(replacement, 0, -1, false), "\n"), "Replacement request")
  end)
end)

h.test("deleting a draft discards it and allows a fresh request", function()
  with_editor(function(f)
    h.truthy(codex.ask("Discard this request"))
    vim.cmd("bdelete!")
    vim.api.nvim_set_current_buf(f.bufnr)
    h.truthy(codex.ask("Fresh request"))
    local text = table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "\n")
    h.contains(text, "Fresh request")
    h.eq(nil, text:find("Discard this request", 1, true))
  end)
end)

h.test("diagnostics reject a changed source instead of applying stale selection lines", function()
  with_editor(function(f)
    h.truthy(codex.ask(nil, 2, 2))
    local draft = vim.api.nvim_get_current_buf()
    local before = vim.api.nvim_buf_get_lines(draft, 0, -1, false)
    vim.api.nvim_buf_set_lines(f.bufnr, 0, 0, false, { "new first line" })
    local namespace = vim.api.nvim_create_namespace("codex_ask_changed_test")
    vim.diagnostic.set(namespace, f.bufnr, {
      { lnum = 1, col = 0, message = "now on a different line", severity = vim.diagnostic.severity.WARN },
    })
    h.eq(false, require("codex.ask").add_diagnostics())
    h.eq(before, vim.api.nvim_buf_get_lines(draft, 0, -1, false))
    h.contains(table.concat(f.notifications, "\n"), "source changed")
    vim.diagnostic.reset(namespace, f.bufnr)
  end)
end)

h.test("ask window failures clean up without changing the editor", function()
  with_editor(function(f)
    local original_open = vim.api.nvim_open_win
    rawset(vim.api, "nvim_open_win", function()
      error("simulated window failure")
    end)
    local ok, result = pcall(codex.ask, "Explain")
    rawset(vim.api, "nvim_open_win", original_open)
    h.eq(true, ok)
    h.eq(false, result)
    h.eq(f.bufnr, vim.api.nvim_get_current_buf())
    h.eq(0, #f.sends)
    h.truthy(codex.ask("Try again"))
  end)
end)
