local h = require("tests.harness")
local codex = require("codex")

local function with_selection(callback)
  local original_buf = vim.api.nvim_get_current_buf()
  local bufnr = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_buf_set_name(bufnr, "/tmp/codex-selection-hint.lua")
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { "local first = 1", "local second = 2", "return first + second" })
  vim.api.nvim_set_current_buf(bufnr)
  local ok, err = xpcall(function()
    callback(bufnr)
  end, debug.traceback)
  vim.api.nvim_feedkeys(vim.keycode("<Esc>"), "nx", false)
  codex.setup({ selection = { enabled = false } })
  codex._reset()
  pcall(vim.keymap.del, "x", "<F5>")
  pcall(vim.keymap.del, "x", "<F6>")
  vim.api.nvim_set_current_buf(original_buf)
  vim.api.nvim_buf_delete(bufnr, { force = true })
  if not ok then
    error(err, 0)
  end
end

local function marks(bufnr)
  return vim.api.nvim_buf_get_extmarks(
    bufnr,
    vim.api.nvim_get_namespaces().codex_nvim_selection,
    0,
    -1,
    { details = true }
  )
end

h.test("visual selection shows mapped actions below its last line and clears on exit", function()
  with_selection(function(bufnr)
    codex.setup({ selection = { keymaps = { ask = "<F5>", edit = "<F6>" } } })
    vim.cmd("normal! ggVj")
    require("codex.selection").update()
    local found = marks(bufnr)
    h.eq(1, #found)
    h.eq(1, found[1][2])
    local label = found[1][4].virt_lines[1][1][1]
    h.contains(label, "<F5>: Ask")
    h.contains(label, "<F6>: Edit")
    h.eq(3, vim.api.nvim_buf_line_count(bufnr))
    vim.cmd("normal! k")
    require("codex.selection").update()
    h.eq(0, marks(bufnr)[1][2])
    vim.api.nvim_feedkeys(vim.keycode("<Esc>"), "nx", false)
    require("codex.selection").update()
    h.eq({}, marks(bufnr))
  end)
end)

h.test("selection hints preserve existing mappings and only advertise available actions", function()
  with_selection(function(bufnr)
    vim.keymap.set("x", "<F5>", ":echo 'existing'<CR>")
    codex.setup({ selection = { keymaps = { ask = "<F5>", edit = "<F6>" } } })
    h.eq(":echo 'existing'<CR>", vim.fn.maparg("<F5>", "x"))
    vim.cmd("normal! ggV")
    require("codex.selection").update()
    local label = marks(bufnr)[1][4].virt_lines[1][1][1]
    h.eq(nil, label:find("Ask", 1, true))
    h.contains(label, "<F6>: Edit")
    codex.setup({ selection = { enabled = false } })
    h.eq(":echo 'existing'<CR>", vim.fn.maparg("<F5>", "x"))
    h.eq("", vim.fn.maparg("<F6>", "x"))
    h.eq({}, marks(bufnr))
  end)
end)

h.test("selection hint settings keep usable mappings and respect buffer overrides", function()
  with_selection(function(bufnr)
    codex.setup({ selection = { hint = false, keymaps = { ask = "<F5>", edit = false } } })
    vim.cmd("normal! ggV")
    require("codex.selection").update()
    h.eq({}, marks(bufnr))
    h.eq(":<C-U>CodexAskVisual<CR>", vim.fn.maparg("<F5>", "x"))
    h.eq("", vim.fn.maparg("<F6>", "x"))
    codex.setup({ selection = { keymaps = { ask = "<F5>", edit = "<F6>" } } })
    vim.keymap.set("x", "<F5>", ":echo 'buffer action'<CR>", { buf = bufnr })
    require("codex.selection").update()
    local label = marks(bufnr)[1][4].virt_lines[1][1][1]
    h.eq(nil, label:find("Ask", 1, true))
    h.contains(label, "Edit")
    codex.setup({ selection = { enabled = false } })
    h.eq(":echo 'buffer action'<CR>", vim.fn.maparg("<F5>", "x"))
    vim.keymap.del("x", "<F5>", { buf = bufnr })
    h.eq("", vim.fn.maparg("<F5>", "x"))
  end)
end)

h.test("the advertised edit mapping opens a request with the selected text without sending", function()
  with_selection(function(bufnr)
    codex.setup({ cwd = "nvim", selection = { keymaps = { ask = "<F5>", edit = "<F6>" } } })
    vim.cmd("normal! gg06lvj2l")
    vim.api.nvim_feedkeys(vim.keycode("<F6>zz<Esc>"), "xt", false)
    h.eq("codex://ask", vim.api.nvim_buf_get_name(0))
    local text = table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "\n")
    h.contains(text, "change")
    h.contains(text, "\nzz\n")
    h.contains(text, "first = 1\nlocal sec")
    h.eq(nil, text:find("return first", 1, true))
    h.eq(false, require("codex.terminal").is_running())
    require("codex.ask").hide()
    h.eq(bufnr, vim.api.nvim_get_current_buf())
  end)
end)
